### ISSUE TITLE
Initial Design for Header {1}

### ISSUE THREAD

**Issue by mtsmachado8** [mtsmachado8/bubbles#1]
Make the initial design for header with flexbox.
Please, make it as a component because it will change a lot.

![image](https://user-images.githubusercontent.com/11022437/98662877-2700e980-2327-11eb-8052-084b85ee72ae.png)

Layout XD:https://xd.adobe.com/view/2ca508a9-8ba1-4161-abb1-46d9b4ff1706-79f6/screen/8b5b5ab6-acda-4c99-acbf-069dcb105043/specs/

**Comment by MatheusDomingues** [comment]
[0:10] Making the styles for Header
