### ISSUE TITLE
Make the Bubble component {3}

### ISSUE THREAD

**Issue by mtsmachado8** [mtsmachado8/bubbles#2]
Make the design for Bubble List Item component.It will be clicable.

When the homepage revalidade, i want to see every bubble inserted on database sorted by creation. (Newer first).

Should have as props:
title
description
labels: String[]
createdDate
avatarUrl
![image](https://user-images.githubusercontent.com/11022437/98660273-df2c9300-2323-11eb-91c5-58a321ce1a56.png)

Design XD: https://xd.adobe.com/view/2ca508a9-8ba1-4161-abb1-46d9b4ff1706-79f6/screen/8b5b5ab6-acda-4c99-acbf-069dcb105043/specs/

**Comment by MatheusDomingues** [comment]
[3:50] Making the responsive Bubble List Item component with alternative avatar image and new variables colors
