### ISSUE TITLE
Bugs + Technical Debts

### ISSUE THREAD

**Issue by mtsmachado8** [mtsmachado8/bubbles#21]
Issue created to map our Technical Debts

**Comment by mtsmachado8** [comment]
- Conteúdo do modal não está renderizando conteúdo diferente
- Data com formato diferente.
- Quadrado girado do lado do avatar

**Comment by MatheusDomingues** [comment]
- FloatingButton com quadrado preto após o click

**Comment by MatheusDomingues** [comment]
- Imagem do Modal no modo responsivo mal posicionada

**Comment by MatheusDomingues** [comment]
- Area de comentários muito pequena quando os detalhes do bubble são menores

**Comment by MatheusDomingues** [comment]
(All of the above are resolved)

**Comment by MatheusDomingues** [comment]
- Margin bottom in the home page
- Deploy in Vercel

**Comment by MatheusDomingues** [comment]
- Renderizing the labels

**Comment by MatheusDomingues** [comment]
- Calculation of comment time posted

**Comment by MatheusDomingues** [comment]
- Deploy on Vercel
- Display the comments in the BubbleDetails

**Comment by MatheusDomingues** [comment]
- Environment Variables (GoogleLogin and GoogleLogout in the component NewComment and NewBubbleModal)

**Comment by mtsmachado8** [comment]
- horizontal scroll is appearing on mobile version. This should work
<img width="1080" alt="Screen Shot 2020-11-27 at 21 47 53" src="https://user-images.githubusercontent.com/11022437/100490534-cd583780-30fa-11eb-9035-c6660f78a6da.png">

**Comment by MatheusDomingues** [comment]
- [] On deploy, when u create a new bubble, u can't access that new bubble page.

**Comment by mtsmachado8** [comment]
[] When i click configure bubbles the color should be the one i chose on creation. Also it should not have a description if i didn't type one
![Uploading image.png…]()

**Comment by mtsmachado8** [comment]
- [ ] Change the text of the Button to 'Comment'. It looks weird on mobile and there is no need for the word 'here'.
![image](https://user-images.githubusercontent.com/11022437/102488212-77681700-404a-11eb-815c-7affb7305a6a.png)

**Comment by mtsmachado8** [comment]
- [ ] We can change 'Login with google' to just 'Login' 
![image](https://user-images.githubusercontent.com/11022437/102488364-b0a08700-404a-11eb-9493-47e9d46a2682.png)

**Comment by mtsmachado8** [comment]
- [ ] Once i'am already logged in, i would like that the main action to take is comment, so the button with must "attention" from the user (The purple one) should be called Comment (there's no need for the words 'with Mateus'. 
![image](https://user-images.githubusercontent.com/11022437/102488550-f9584000-404a-11eb-99a3-2efdfe6b89f6.png)
I would like the buttons Logout (ghost) Cancel (ghost) and Comment (primary/purple) in that specific order

**Comment by MatheusDomingues** [comment]
- [] Notion It isn't saving to the database.

**Comment by MatheusDomingues** [comment]
- [ ] Bug with Quiz on Menu of Notion

**Comment by mtsmachado8** [comment]
[] Bug with Image Optimization
![image](https://user-images.githubusercontent.com/11022437/108221808-f3e4a800-7116-11eb-9f41-c0d1f6076e26.png)

**Comment by mtsmachado8** [comment]
- [ ] index page is loading unsorted and only them sorting by likes. I would like it to be already sorted (on getProps method)

**Comment by mtsmachado8** [comment]
- [ ] Feature -> Like bubble outside it (like it on index page)
