### ISSUE TITLE
Make a Floating Botton and a Modal on next {2}

### ISSUE THREAD

**Issue by mtsmachado8** [mtsmachado8/bubbles#3]
When i click on the plus button a modal will show up with route /bubbles/new so i can start making my new bubble.
Button:
![image](https://user-images.githubusercontent.com/11022437/98660846-88738900-2324-11eb-9364-abddc227d8ad.png)
**Obs:** Its not centralized on XD for whatever reason, please make it centralized. Its a + white text

I think you'll need a static page inside bubbles folder with name new.tsx, something like that.

Just make it render a new page. The design of that page will be on other task.

Can make it with page initially if you like

**Comment by MatheusDomingues** [comment]
[2:50] Making the floating button and the responsive modal component
