### ISSUE TITLE
Modal with a bubble {2}

### ISSUE THREAD

**Issue by mtsmachado8** [mtsmachado8/bubbles#4]
We will have bubbles located on /bubbles/id. When i click a bubble item on homepage a modal with the details of that bubble should show up.

![image](https://user-images.githubusercontent.com/11022437/99157042-9b7bb580-26a4-11eb-9dce-ead0d22435e9.png)

Those details of author, title and content will be filled. (the button Submit will desappear, the description too)

**Comment by MatheusDomingues** [comment]
[5:30] Fixing bugs, making details for styles and studiyng the modal.

**Comment by MatheusDomingues** [comment]
[3] - Making the modal with bubble details
