### ISSUE TITLE
New Bubble Modal {8}

### ISSUE THREAD

**Issue by mtsmachado8** [mtsmachado8/bubbles#5]
Make the design of a NewBubble modal component.
This modal should have a title, a description, a text area to write my bubble details and a button to submit my bubble anonimously. (The image of my avatar should be the anonimous image since iam not logged in).

When i click on submit anonimously, the modal should close and a new Bubble item should appear on homepage.

You can make a componente for this Editable Bubble or more than one component for the main parts, so you can reuse it. 
I suggest those components inside **Folder Components**(you can make more as you like):
**Folder Elements:**
- Button (with ghost and primary variations)
- WriteTextArea with the right colors and so on...(**obs:** every color should be on theme as a css variable)
- EditableTitle with transparent background.
- EditableDescription with transparent background.
- Avatar (wich receives a avatarUrl or null so we can render the anonimous svg)

**Folder Modules**
- EditableBubble itself, wich composes those components together.

![image](https://user-images.githubusercontent.com/11022437/98661268-00da4a00-2325-11eb-9cad-e4839e9157e5.png)

Layout XD: https://xd.adobe.com/view/2ca508a9-8ba1-4161-abb1-46d9b4ff1706-79f6/screen/f119c19e-b526-4fa1-bb65-8274bd7dc5b9/specs/

**Comment by MatheusDomingues** [comment]
[5] - Making the New Bubble Modal style

**Comment by MatheusDomingues** [comment]
[2] - Connecting the New Bubble Modal with API to create new bubble
