### ISSUE TITLE
Spike + Login with google (one tap login) {8}

### ISSUE THREAD

**Issue by mtsmachado8** [mtsmachado8/bubbles#6]
I should be able to login to post a new bubble. When i click on login with google, a pop up will appear bellow the button and allow me to login.

Once i login, a new User will be created(in case a user with that email doesnt exist) and save my avatarUrl,name, email on databse.

Them i can post a new Bubble with my info as author.
![image](https://user-images.githubusercontent.com/11022437/99156899-9b2eea80-26a3-11eb-8c10-bd7d3d692c41.png)

One tap login Web Docs: https://developers.google.com/identity/one-tap/web/guides/get-google-api-clientid 

In the first time i login i want to create a new user on postgres, so whe can show this user on posted bubbles.

XD Link: https://xd.adobe.com/view/2ca508a9-8ba1-4161-abb1-46d9b4ff1706-79f6/screen/44910951-058f-4af0-b5dd-afbf0856424f/specs/

**Comment by MatheusDomingues** [comment]
[5:20] - Fixing bugs and find a way to implement google one tap login

**Comment by MatheusDomingues** [comment]
[4] - Making the content to receiv the Google User information

**Comment by MatheusDomingues** [comment]
[8] - Making the Database Configs for received data and fixing responsive modal
